name: Test
on:
  push:
    branches:
      - main
jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: install a11ywatch
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install a11ywatch_cli
      - name: Build A11yWatch Service
        shell: bash
        run: a11ywatch --version
      # - name: Start A11yWatch Service
      #   shell: bash
      #   run: a11ywatch start --standalone --local
