name: Test
on:
  push:
    branches:
      - main
jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - name: install a11ywatch
        run: cargo install a11ywatch_cli
      - name: Build A11yWatch Service
        shell: bash
        run: a11ywatch build --standalone --local
      - name: Start A11yWatch Service
        shell: bash
        run: a11ywatch start --standalone --local
