name: Test
on:
  push:
    branches:
      - main
jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - name: test cargo
        run: cargo install a11ywatch_cli
      - name: test cargo
        run: a11ywatch build
