name: Test
on:
  push:
    branches:
      - main
jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - name: a11ywatch cache
        uses: actions/cache@v3
        id: a11watch-cache
        with:
          path: |
            /usr/local/lib/node_modules/@a11ywatch/a11ywatch
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: cargo cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: install a11ywatch
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install a11ywatch_cli
      - name: build
        if: steps.a11watch-cache.outputs.cache-hit != 'true'
        run: a11ywatch build --local
      - name: Start A11yWatch Service
        run: a11ywatch start --local
      - name: Scan
        run: a11ywatch scan --url https://www.google.com -s
