name: Test
on:
  push:
    branches:
      - main
jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: /usr/local/lib/node_modules/@a11ywatch/a11ywatch
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: install a11ywatch
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install a11ywatch_cli
      - name: build
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: a11ywatch build --standalone --local
      - name: Start A11yWatch Service
        run: a11ywatch start --standalone --local
      - name: Scan
        run: a11ywatch scan --url https://www.google.com
